
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 20 2024 13:19:50 IST (Nov 20 2024 07:49:50 UTC)

// Verification Directory fv/ldd_16_1_decoder 

module ldd_16_1_decoder(sign, r_out, e, frac, z, inf, in, allone);
  input [15:0] in;
  output sign, z, inf, allone;
  output [4:0] r_out;
  output [0:0] e;
  output [11:0] frac;
  wire [15:0] in;
  wire sign, z, inf, allone;
  wire [4:0] r_out;
  wire [0:0] e;
  wire [11:0] frac;
  wire SUB_UNS_OP_n_0, SUB_UNS_OP_n_1, SUB_UNS_OP_n_2, SUB_UNS_OP_n_3,
       SUB_UNS_OP_n_4, SUB_UNS_OP_n_5, SUB_UNS_OP_n_6, SUB_UNS_OP_n_8;
  wire SUB_UNS_OP_n_10, SUB_UNS_OP_n_12, SUB_UNS_OP_n_14,
       SUB_UNS_OP_n_16, SUB_UNS_OP_n_18, SUB_UNS_OP_n_20,
       SUB_UNS_OP_n_22, SUB_UNS_OP_n_24;
  wire SUB_UNS_OP_n_26, SUB_UNS_OP_n_28, SUB_UNS_OP_n_30, n_0, n_1,
       n_2, n_3, n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_21, n_22, n_23, n_24, n_25, n_26, n_27, n_28;
  wire n_29, n_30, n_31, n_32, n_33, n_34, n_35, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_44;
  wire n_45, n_46, n_47, n_48, n_49, n_50, n_51, n_52;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_74, n_75, n_76;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_84;
  wire n_85, n_86, n_87, n_88, n_89, n_90, n_91, n_92;
  wire n_93, n_94, n_95, n_96, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_115, n_116;
  wire n_117, n_118, n_119, n_120, n_121, n_122, n_123, n_124;
  wire n_125, n_126, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144;
  assign sign = in[15];
  XNOR2X1 g2750__2398(.A (r_out[4]), .B (n_130), .Y (r_out[2]));
  XNOR2X1 g2751__5107(.A (r_out[4]), .B (n_129), .Y (r_out[3]));
  XNOR2X1 g2752__6260(.A (r_out[4]), .B (n_126), .Y (r_out[1]));
  NOR4X1 g2753__4319(.A (n_70), .B (n_95), .C (n_72), .D (n_128), .Y
       (n_130));
  NOR4X1 g2754__8428(.A (n_94), .B (n_119), .C (n_106), .D (n_128), .Y
       (n_129));
  OAI211X1 g2755__5526(.A0 (n_5), .A1 (n_108), .B0 (n_127), .C0 (n_92),
       .Y (e));
  NAND4XL g2756__6783(.A (n_109), .B (n_88), .C (n_115), .D (n_122), .Y
       (frac[11]));
  NOR4X1 g2757__3680(.A (n_82), .B (n_100), .C (n_116), .D (n_121), .Y
       (n_127));
  NAND3BXL g2758__1617(.AN (n_125), .B (n_108), .C (n_107), .Y (n_128));
  OR4X1 g2759__2802(.A (n_87), .B (n_101), .C (n_89), .D (n_120), .Y
       (frac[10]));
  XNOR2X1 g2760__1705(.A (r_out[4]), .B (n_123), .Y (r_out[0]));
  NOR4X1 g2761__5122(.A (n_58), .B (n_125), .C (n_68), .D (n_124), .Y
       (n_126));
  OR2X1 g2762__8246(.A (n_95), .B (n_119), .Y (n_124));
  NAND4XL g2763__7098(.A (n_117), .B (n_91), .C (n_81), .D (n_99), .Y
       (frac[9]));
  NOR4X1 g2764__6131(.A (n_118), .B (n_114), .C (n_68), .D (n_106), .Y
       (n_123));
  NAND3BXL g2765__1881(.AN (allone), .B (n_47), .C (n_48), .Y (n_125));
  OAI211X1 g2766__5115(.A0 (n_5), .A1 (n_93), .B0 (n_80), .C0 (n_113),
       .Y (frac[8]));
  AOI22XL g2767__7482(.A0 (in[0]), .A1 (n_111), .B0 (n_18), .B1
       (n_102), .Y (n_122));
  OAI22XL g2768__4733(.A0 (n_19), .A1 (n_112), .B0 (n_9), .B1 (n_93),
       .Y (n_121));
  OAI222XL g2769__6161(.A0 (n_19), .A1 (n_105), .B0 (n_5), .B1 (n_103),
       .C0 (n_21), .C1 (n_93), .Y (n_120));
  NAND2XL g2770__9315(.A (n_52), .B (n_112), .Y (n_118));
  NAND2XL g2771__9945(.A (n_86), .B (n_110), .Y (frac[7]));
  NAND2XL g2772__2883(.A (n_103), .B (n_112), .Y (n_119));
  AOI22XL g2773__2346(.A0 (in[0]), .A1 (n_106), .B0 (n_18), .B1 (n_94),
       .Y (n_117));
  OAI22XL g2774__1666(.A0 (n_21), .A1 (n_103), .B0 (n_23), .B1 (n_105),
       .Y (n_116));
  AOI22XL g2775__7410(.A0 (n_20), .A1 (n_106), .B0 (n_22), .B1 (n_94),
       .Y (n_115));
  NAND3BXL g2776__6417(.AN (n_72), .B (n_107), .C (n_78), .Y (n_114));
  OAI211X1 g2777__5477(.A0 (n_19), .A1 (n_73), .B0 (n_85), .C0 (n_83),
       .Y (frac[6]));
  AOI221X1 g2778__2398(.A0 (n_20), .A1 (n_1), .B0 (n_22), .B1 (n_72),
       .C0 (n_98), .Y (n_113));
  NOR3XL g2779__5107(.A (r_out[4]), .B (n_49), .C (n_96), .Y (allone));
  INVXL g2780(.A (n_112), .Y (n_111));
  AOI221X1 g2781__6260(.A0 (n_18), .A1 (n_1), .B0 (n_22), .B1 (n_70),
       .C0 (n_97), .Y (n_110));
  AOI221X1 g2782__4319(.A0 (n_24), .A1 (n_72), .B0 (n_12), .B1 (n_70),
       .C0 (n_104), .Y (n_109));
  OAI221X1 g2783__8428(.A0 (n_19), .A1 (n_69), .B0 (n_5), .B1 (n_73),
       .C0 (n_84), .Y (frac[5]));
  NAND4X1 g2784__5526(.A (n_34), .B (n_37), .C (n_35), .D (n_90), .Y
       (n_112));
  INVX1 g2785(.A (n_106), .Y (n_105));
  OAI211X1 g2786__6783(.A0 (n_5), .A1 (n_69), .B0 (n_59), .C0 (n_75),
       .Y (frac[4]));
  OAI22XL g2787__3680(.A0 (n_9), .A1 (n_78), .B0 (n_11), .B1 (n_71), .Y
       (n_104));
  NAND3BXL g2788__1617(.AN (n_55), .B (n_39), .C (n_79), .Y (n_108));
  NAND2BXL g2789__2802(.AN (n_96), .B (n_49), .Y (n_107));
  NOR3BXL g2790__1705(.AN (n_34), .B (n_35), .C (n_2), .Y (n_106));
  INVXL g2791(.A (n_103), .Y (n_102));
  OAI22XL g2792__5122(.A0 (n_23), .A1 (n_78), .B0 (n_11), .B1 (n_73),
       .Y (n_101));
  OAI22XL g2793__8246(.A0 (n_11), .A1 (n_78), .B0 (n_27), .B1 (n_69),
       .Y (n_100));
  OA22X1 g2794__7098(.A0 (n_21), .A1 (n_78), .B0 (n_11), .B1 (n_69), .Y
       (n_99));
  OAI22XL g2795__6131(.A0 (n_19), .A1 (n_78), .B0 (n_9), .B1 (n_69), .Y
       (n_98));
  OAI22XL g2796__1881(.A0 (n_5), .A1 (n_78), .B0 (n_21), .B1 (n_73), .Y
       (n_97));
  NAND4BX1 g2797__5115(.AN (n_37), .B (n_34), .C (n_35), .D (n_79), .Y
       (n_103));
  INVX1 g2798(.A (n_94), .Y (n_93));
  AOI221X1 g2799__7482(.A0 (n_28), .A1 (n_68), .B0 (n_30), .B1 (n_58),
       .C0 (n_66), .Y (n_92));
  AOI221X1 g2800__4733(.A0 (n_24), .A1 (n_68), .B0 (n_12), .B1 (n_58),
       .C0 (n_63), .Y (n_91));
  NOR2XL g2801__6161(.A (n_40), .B (n_2), .Y (n_90));
  OAI221X1 g2802__9315(.A0 (n_29), .A1 (n_52), .B0 (n_31), .B1 (n_43),
       .C0 (n_76), .Y (n_89));
  AOI221X1 g2803__9945(.A0 (n_26), .A1 (n_68), .B0 (n_28), .B1 (n_58),
       .C0 (n_64), .Y (n_88));
  OR3X1 g2804__2883(.A (n_2), .B (n_39), .C (n_55), .Y (n_96));
  NAND2XL g2805__2346(.A (n_71), .B (n_78), .Y (n_95));
  NOR2XL g2806__1666(.A (n_34), .B (n_2), .Y (n_94));
  OAI22XL g2807__7410(.A0 (n_9), .A1 (n_71), .B0 (n_25), .B1 (n_69), .Y
       (n_87));
  AOI221X1 g2808__6417(.A0 (n_24), .A1 (n_51), .B0 (n_12), .B1 (n_42),
       .C0 (n_74), .Y (n_86));
  AOI221X1 g2809__5477(.A0 (n_22), .A1 (n_68), .B0 (n_8), .B1 (n_58),
       .C0 (n_61), .Y (n_85));
  AOI221X1 g2810__2398(.A0 (n_20), .A1 (n_68), .B0 (n_22), .B1 (n_58),
       .C0 (n_60), .Y (n_84));
  OAI221X1 g2811__5107(.A0 (n_21), .A1 (n_52), .B0 (n_23), .B1 (n_43),
       .C0 (n_77), .Y (frac[3]));
  AOI22XL g2812__6260(.A0 (in[0]), .A1 (n_1), .B0 (n_20), .B1 (n_70),
       .Y (n_83));
  OAI22XL g2813__4319(.A0 (n_25), .A1 (n_71), .B0 (n_13), .B1 (n_73),
       .Y (n_82));
  AOI22XL g2814__8428(.A0 (n_22), .A1 (n_1), .B0 (n_8), .B1 (n_72), .Y
       (n_81));
  AOI221X1 g2815__5526(.A0 (n_10), .A1 (n_68), .B0 (n_24), .B1 (n_58),
       .C0 (n_62), .Y (n_80));
  INVX1 g2816(.A (n_2), .Y (n_79));
  AOI22XL g2817__6783(.A0 (in[0]), .A1 (n_68), .B0 (n_18), .B1 (n_58),
       .Y (n_77));
  OR4X1 g2819__3680(.A (n_50), .B (n_45), .C (n_41), .D (n_54), .Y
       (n_78));
  AOI22XL g2820__1617(.A0 (n_12), .A1 (n_68), .B0 (n_26), .B1 (n_58),
       .Y (n_76));
  AOI22XL g2821__2802(.A0 (n_18), .A1 (n_68), .B0 (n_20), .B1 (n_58),
       .Y (n_75));
  OAI22XL g2822__1705(.A0 (n_9), .A1 (n_67), .B0 (n_11), .B1 (n_57), .Y
       (n_74));
  INVX1 g2823(.A (n_73), .Y (n_72));
  NAND3BX1 g2824__5122(.AN (n_54), .B (n_45), .C (n_44), .Y (n_73));
  INVX1 g2825(.A (n_1), .Y (n_71));
  OAI222XL g2826__8246(.A0 (n_5), .A1 (n_57), .B0 (n_19), .B1 (n_52),
       .C0 (n_21), .C1 (n_43), .Y (frac[2]));
  INVX1 g2828(.A (n_70), .Y (n_69));
  INVX1 g2829(.A (n_68), .Y (n_67));
  OAI22XL g2830__7098(.A0 (n_14), .A1 (n_52), .B0 (n_32), .B1 (n_43),
       .Y (n_66));
  OAI22XL g2831__6131(.A0 (n_5), .A1 (n_52), .B0 (n_19), .B1 (n_43), .Y
       (frac[1]));
  NOR2BX1 g2832__1881(.AN (n_41), .B (n_54), .Y (n_65));
  NOR2XL g2833__5115(.A (n_44), .B (n_54), .Y (n_70));
  NOR2X1 g2834__7482(.A (n_38), .B (n_56), .Y (n_68));
  OAI22XL g2835__4733(.A0 (n_31), .A1 (n_52), .B0 (n_14), .B1 (n_43),
       .Y (n_64));
  OAI22XL g2836__6161(.A0 (n_27), .A1 (n_52), .B0 (n_29), .B1 (n_43),
       .Y (n_63));
  OAI22XL g2837__9315(.A0 (n_13), .A1 (n_52), .B0 (n_27), .B1 (n_43),
       .Y (n_62));
  OAI22XL g2838__9945(.A0 (n_11), .A1 (n_52), .B0 (n_25), .B1 (n_43),
       .Y (n_61));
  OAI22XL g2839__2883(.A0 (n_9), .A1 (n_52), .B0 (n_11), .B1 (n_43), .Y
       (n_60));
  AOI22XL g2840__2346(.A0 (n_22), .A1 (n_51), .B0 (n_8), .B1 (n_42), .Y
       (n_59));
  INVX1 g2841(.A (n_58), .Y (n_57));
  NAND2XL g2842__1666(.A (n_36), .B (n_53), .Y (n_56));
  NOR2X1 g2843__7410(.A (n_36), .B (n_3), .Y (n_58));
  NAND4XL g2844__6417(.A (n_34), .B (n_35), .C (n_37), .D (n_40), .Y
       (n_55));
  NAND3XL g2845__5477(.A (n_53), .B (n_36), .C (n_38), .Y (n_54));
  INVX1 g2846(.A (n_3), .Y (n_53));
  INVX1 g2847(.A (n_52), .Y (n_51));
  NAND2X1 g2849__2398(.A (n_0), .B (n_43), .Y (n_52));
  NAND2XL g2850__5107(.A (n_44), .B (n_46), .Y (n_50));
  NOR2XL g2851__6260(.A (n_5), .B (n_43), .Y (frac[0]));
  INVXL g2852(.A (n_48), .Y (z));
  INVXL g2853(.A (n_47), .Y (inf));
  INVX1 g2857(.A (n_43), .Y (n_42));
  OAI22XL g2858__4319(.A0 (n_5), .A1 (n_18), .B0 (in[0]), .B1 (n_19),
       .Y (n_49));
  NAND4XL g2859__8428(.A (n_7), .B (n_16), .C (n_15), .D (n_17), .Y
       (n_48));
  NAND4XL g2860__5526(.A (n_6), .B (n_17), .C (n_16), .D (n_15), .Y
       (n_47));
  AOI22XL g2862__6783(.A0 (n_26), .A1 (n_13), .B0 (n_12), .B1 (n_27),
       .Y (n_46));
  OAI22XL g2863__3680(.A0 (n_29), .A1 (n_26), .B0 (n_27), .B1 (n_28),
       .Y (n_45));
  AOI22XL g2864__1617(.A0 (n_30), .A1 (n_29), .B0 (n_28), .B1 (n_31),
       .Y (n_44));
  XNOR2X1 g2865__2802(.A (n_33), .B (r_out[4]), .Y (n_43));
  AOI22XL g2866__1705(.A0 (n_12), .A1 (n_25), .B0 (n_24), .B1 (n_13),
       .Y (n_41));
  AOI22XL g2867__5122(.A0 (n_22), .A1 (n_21), .B0 (n_20), .B1 (n_23),
       .Y (n_40));
  OAI22XL g2868__8246(.A0 (n_21), .A1 (n_18), .B0 (n_19), .B1 (n_20),
       .Y (n_39));
  XNOR2X1 g2869__7098(.A (n_31), .B (n_14), .Y (n_38));
  AOI22XL g2870__6131(.A0 (n_8), .A1 (n_23), .B0 (n_22), .B1 (n_9), .Y
       (n_37));
  XNOR2X1 g2871__1881(.A (n_14), .B (n_32), .Y (n_36));
  AOI22XL g2872__5115(.A0 (n_10), .A1 (n_9), .B0 (n_8), .B1 (n_11), .Y
       (n_35));
  AOI22XL g2873__7482(.A0 (n_24), .A1 (n_11), .B0 (n_10), .B1 (n_25),
       .Y (n_34));
  INVX1 g2875(.A (n_31), .Y (n_30));
  INVX1 g2876(.A (n_29), .Y (n_28));
  INVX1 g2877(.A (n_27), .Y (n_26));
  INVX1 g2878(.A (n_25), .Y (n_24));
  INVX1 g2879(.A (n_23), .Y (n_22));
  INVX1 g2880(.A (n_21), .Y (n_20));
  INVX1 g2881(.A (n_19), .Y (n_18));
  AOI22XL g2882__4733(.A0 (in[13]), .A1 (n_4), .B0 (in[15]), .B1
       (n_143), .Y (n_33));
  AOI22XL g2883__6161(.A0 (in[12]), .A1 (n_4), .B0 (in[15]), .B1
       (n_142), .Y (n_32));
  AOI22XL g2884__9315(.A0 (in[10]), .A1 (n_4), .B0 (in[15]), .B1
       (n_140), .Y (n_31));
  AOI22XL g2885__9945(.A0 (in[9]), .A1 (n_4), .B0 (in[15]), .B1
       (n_139), .Y (n_29));
  AOI22XL g2886__2883(.A0 (in[8]), .A1 (n_4), .B0 (in[15]), .B1
       (n_138), .Y (n_27));
  AOI22XL g2887__2346(.A0 (in[6]), .A1 (n_4), .B0 (in[15]), .B1
       (n_136), .Y (n_25));
  AOI22XL g2888__1666(.A0 (in[3]), .A1 (n_4), .B0 (in[15]), .B1
       (n_133), .Y (n_23));
  AOI22X1 g2889__7410(.A0 (in[2]), .A1 (n_4), .B0 (in[15]), .B1
       (n_132), .Y (n_21));
  AOI22X1 g2890__6417(.A0 (in[1]), .A1 (n_4), .B0 (in[15]), .B1
       (n_131), .Y (n_19));
  INVX1 g2891(.A (n_13), .Y (n_12));
  INVX1 g2892(.A (n_11), .Y (n_10));
  INVX1 g2893(.A (n_9), .Y (n_8));
  NOR4X1 g2894__5477(.A (in[15]), .B (in[14]), .C (in[13]), .D
       (in[12]), .Y (n_7));
  NOR4X1 g2895__2398(.A (n_4), .B (in[14]), .C (in[13]), .D (in[12]),
       .Y (n_6));
  NOR4X1 g2896__5107(.A (in[3]), .B (in[2]), .C (in[1]), .D (in[0]), .Y
       (n_17));
  NOR4X1 g2897__6260(.A (in[11]), .B (in[10]), .C (in[9]), .D (in[8]),
       .Y (n_16));
  NOR4X1 g2898__4319(.A (in[7]), .B (in[6]), .C (in[5]), .D (in[4]), .Y
       (n_15));
  AOI22XL g2899__8428(.A0 (in[11]), .A1 (n_4), .B0 (in[15]), .B1
       (n_141), .Y (n_14));
  AOI22XL g2900__5526(.A0 (in[7]), .A1 (n_4), .B0 (in[15]), .B1
       (n_137), .Y (n_13));
  AOI22XL g2901__6783(.A0 (in[14]), .A1 (n_4), .B0 (in[15]), .B1
       (n_144), .Y (r_out[4]));
  AOI22X1 g2902__3680(.A0 (in[5]), .A1 (n_4), .B0 (in[15]), .B1
       (n_135), .Y (n_11));
  AOI22X1 g2903__1617(.A0 (in[4]), .A1 (n_4), .B0 (in[15]), .B1
       (n_134), .Y (n_9));
  INVX1 g2904(.A (in[0]), .Y (n_5));
  INVX1 g2905(.A (in[15]), .Y (n_4));
  NAND2BX1 g2__2802(.AN (n_0), .B (n_43), .Y (n_3));
  NAND4BX1 g2906__1705(.AN (n_45), .B (n_46), .C (n_44), .D (n_65), .Y
       (n_2));
  NOR4BX1 g2907__5122(.AN (n_44), .B (n_45), .C (n_46), .D (n_54), .Y
       (n_1));
  XOR2XL g2908__8246(.A (n_33), .B (n_32), .Y (n_0));
  XNOR2X1 SUB_UNS_OP_g228__7098(.A (SUB_UNS_OP_n_30), .B (in[14]), .Y
       (n_144));
  AOI21XL SUB_UNS_OP_g229__6131(.A0 (in[13]), .A1 (SUB_UNS_OP_n_28),
       .B0 (SUB_UNS_OP_n_30), .Y (n_143));
  NOR2XL SUB_UNS_OP_g230__1881(.A (in[13]), .B (SUB_UNS_OP_n_28), .Y
       (SUB_UNS_OP_n_30));
  OA21X1 SUB_UNS_OP_g231__5115(.A0 (SUB_UNS_OP_n_2), .A1
       (SUB_UNS_OP_n_26), .B0 (SUB_UNS_OP_n_28), .Y (n_142));
  NAND2XL SUB_UNS_OP_g232__7482(.A (SUB_UNS_OP_n_2), .B
       (SUB_UNS_OP_n_26), .Y (SUB_UNS_OP_n_28));
  AOI21XL SUB_UNS_OP_g233__4733(.A0 (in[11]), .A1 (SUB_UNS_OP_n_24),
       .B0 (SUB_UNS_OP_n_26), .Y (n_141));
  NOR2XL SUB_UNS_OP_g234__6161(.A (in[11]), .B (SUB_UNS_OP_n_24), .Y
       (SUB_UNS_OP_n_26));
  OA21X1 SUB_UNS_OP_g235__9315(.A0 (SUB_UNS_OP_n_5), .A1
       (SUB_UNS_OP_n_22), .B0 (SUB_UNS_OP_n_24), .Y (n_140));
  NAND2XL SUB_UNS_OP_g236__9945(.A (SUB_UNS_OP_n_5), .B
       (SUB_UNS_OP_n_22), .Y (SUB_UNS_OP_n_24));
  AOI21XL SUB_UNS_OP_g237__2883(.A0 (in[9]), .A1 (SUB_UNS_OP_n_20), .B0
       (SUB_UNS_OP_n_22), .Y (n_139));
  NOR2XL SUB_UNS_OP_g238__2346(.A (in[9]), .B (SUB_UNS_OP_n_20), .Y
       (SUB_UNS_OP_n_22));
  OA21X1 SUB_UNS_OP_g239__1666(.A0 (SUB_UNS_OP_n_3), .A1
       (SUB_UNS_OP_n_18), .B0 (SUB_UNS_OP_n_20), .Y (n_138));
  NAND2XL SUB_UNS_OP_g240__7410(.A (SUB_UNS_OP_n_3), .B
       (SUB_UNS_OP_n_18), .Y (SUB_UNS_OP_n_20));
  AOI21XL SUB_UNS_OP_g241__6417(.A0 (in[7]), .A1 (SUB_UNS_OP_n_16), .B0
       (SUB_UNS_OP_n_18), .Y (n_137));
  NOR2XL SUB_UNS_OP_g242__5477(.A (in[7]), .B (SUB_UNS_OP_n_16), .Y
       (SUB_UNS_OP_n_18));
  OA21X1 SUB_UNS_OP_g243__2398(.A0 (SUB_UNS_OP_n_4), .A1
       (SUB_UNS_OP_n_14), .B0 (SUB_UNS_OP_n_16), .Y (n_136));
  NAND2XL SUB_UNS_OP_g244__5107(.A (SUB_UNS_OP_n_4), .B
       (SUB_UNS_OP_n_14), .Y (SUB_UNS_OP_n_16));
  AOI21XL SUB_UNS_OP_g245__6260(.A0 (in[5]), .A1 (SUB_UNS_OP_n_12), .B0
       (SUB_UNS_OP_n_14), .Y (n_135));
  NOR2XL SUB_UNS_OP_g246__4319(.A (in[5]), .B (SUB_UNS_OP_n_12), .Y
       (SUB_UNS_OP_n_14));
  OA21X1 SUB_UNS_OP_g247__8428(.A0 (SUB_UNS_OP_n_0), .A1
       (SUB_UNS_OP_n_10), .B0 (SUB_UNS_OP_n_12), .Y (n_134));
  NAND2XL SUB_UNS_OP_g248__5526(.A (SUB_UNS_OP_n_0), .B
       (SUB_UNS_OP_n_10), .Y (SUB_UNS_OP_n_12));
  AOI21XL SUB_UNS_OP_g249__6783(.A0 (in[3]), .A1 (SUB_UNS_OP_n_8), .B0
       (SUB_UNS_OP_n_10), .Y (n_133));
  NOR2XL SUB_UNS_OP_g250__3680(.A (in[3]), .B (SUB_UNS_OP_n_8), .Y
       (SUB_UNS_OP_n_10));
  OA21X1 SUB_UNS_OP_g251__1617(.A0 (SUB_UNS_OP_n_1), .A1
       (SUB_UNS_OP_n_6), .B0 (SUB_UNS_OP_n_8), .Y (n_132));
  NAND2XL SUB_UNS_OP_g252__2802(.A (SUB_UNS_OP_n_1), .B
       (SUB_UNS_OP_n_6), .Y (SUB_UNS_OP_n_8));
  AOI21XL SUB_UNS_OP_g253__1705(.A0 (in[1]), .A1 (in[0]), .B0
       (SUB_UNS_OP_n_6), .Y (n_131));
  NOR2XL SUB_UNS_OP_g254__5122(.A (in[1]), .B (in[0]), .Y
       (SUB_UNS_OP_n_6));
  INVX1 SUB_UNS_OP_g255(.A (in[10]), .Y (SUB_UNS_OP_n_5));
  INVX1 SUB_UNS_OP_g256(.A (in[6]), .Y (SUB_UNS_OP_n_4));
  INVX1 SUB_UNS_OP_g257(.A (in[8]), .Y (SUB_UNS_OP_n_3));
  INVX1 SUB_UNS_OP_g258(.A (in[12]), .Y (SUB_UNS_OP_n_2));
  INVX1 SUB_UNS_OP_g259(.A (in[2]), .Y (SUB_UNS_OP_n_1));
  INVX1 SUB_UNS_OP_g260(.A (in[4]), .Y (SUB_UNS_OP_n_0));
endmodule

