
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 20 2024 13:12:59 IST (Nov 20 2024 07:42:59 UTC)

// Verification Directory fv/ldd_8_1_decoder 

module ldd_8_1_decoder(sign, r_out, e, frac, z, inf, in, allone);
  input [7:0] in;
  output sign, z, inf, allone;
  output [3:0] r_out, frac;
  output [0:0] e;
  wire [7:0] in;
  wire sign, z, inf, allone;
  wire [3:0] r_out, frac;
  wire [0:0] e;
  wire SUB_UNS_OP_n_0, SUB_UNS_OP_n_1, SUB_UNS_OP_n_2, SUB_UNS_OP_n_4,
       SUB_UNS_OP_n_6, SUB_UNS_OP_n_8, SUB_UNS_OP_n_10, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  assign sign = in[7];
  XNOR2X1 g801__2398(.A (r_out[3]), .B (n_34), .Y (r_out[1]));
  XNOR2X1 g802__5107(.A (r_out[3]), .B (n_33), .Y (r_out[2]));
  XNOR2X1 g803__6260(.A (r_out[3]), .B (n_2), .Y (r_out[0]));
  NOR3XL g804__4319(.A (n_27), .B (n_25), .C (n_31), .Y (n_34));
  OAI2BB1X1 g805__8428(.A0N (in[0]), .A1N (n_29), .B0 (n_32), .Y (e));
  NOR3XL g806__5526(.A (n_1), .B (n_29), .C (n_31), .Y (n_33));
  AOI221X1 g808__6783(.A0 (n_9), .A1 (n_27), .B0 (n_11), .B1 (n_25),
       .C0 (n_26), .Y (n_32));
  OAI221X1 g809__3680(.A0 (n_12), .A1 (n_0), .B0 (n_7), .B1 (n_16), .C0
       (n_30), .Y (frac[3]));
  OR3X1 g810__1617(.A (allone), .B (inf), .C (z), .Y (n_31));
  AOI22XL g811__2802(.A0 (in[0]), .A1 (n_27), .B0 (n_9), .B1 (n_25), .Y
       (n_30));
  OAI221X1 g813__1705(.A0 (n_10), .A1 (n_0), .B0 (n_12), .B1 (n_16),
       .C0 (n_28), .Y (frac[2]));
  NOR4X1 g814__5122(.A (r_out[3]), .B (n_17), .C (n_22), .D (n_24), .Y
       (allone));
  NAND2XL g815__8246(.A (in[0]), .B (n_25), .Y (n_28));
  NOR2BX1 g816__7098(.AN (n_17), .B (n_24), .Y (n_29));
  OAI22XL g817__6131(.A0 (n_3), .A1 (n_0), .B0 (n_10), .B1 (n_16), .Y
       (frac[1]));
  OAI22XL g818__1881(.A0 (n_7), .A1 (n_0), .B0 (n_8), .B1 (n_16), .Y
       (n_26));
  NOR3XL g819__5115(.A (n_20), .B (n_19), .C (n_23), .Y (n_27));
  NOR2BX1 g820__7482(.AN (n_19), .B (n_23), .Y (n_25));
  NAND3BXL g821__4733(.AN (n_23), .B (n_18), .C (n_20), .Y (n_24));
  NOR2XL g822__6161(.A (n_3), .B (n_16), .Y (frac[0]));
  NAND2XL g824__9315(.A (n_16), .B (n_21), .Y (n_23));
  OAI22XL g828__9945(.A0 (n_3), .A1 (n_9), .B0 (in[0]), .B1 (n_10), .Y
       (n_22));
  NOR3XL g829__2883(.A (n_15), .B (in[3]), .C (in[0]), .Y (inf));
  NOR3XL g830__2346(.A (n_14), .B (in[3]), .C (in[0]), .Y (z));
  XNOR2X1 g831__1666(.A (n_8), .B (n_13), .Y (n_21));
  INVX1 g832(.A (n_18), .Y (n_19));
  XNOR2X1 g833__7410(.A (n_12), .B (n_7), .Y (n_20));
  XNOR2X1 g834__6417(.A (n_7), .B (n_8), .Y (n_18));
  OAI22XL g835__5477(.A0 (n_12), .A1 (n_9), .B0 (n_10), .B1 (n_11), .Y
       (n_17));
  XNOR2X1 g836__2398(.A (n_13), .B (r_out[3]), .Y (n_16));
  NAND4BXL g837__5107(.AN (in[6]), .B (n_6), .C (n_5), .D (in[7]), .Y
       (n_15));
  NAND4BXL g838__6260(.AN (in[6]), .B (n_4), .C (n_6), .D (n_5), .Y
       (n_14));
  INVX1 g839(.A (n_12), .Y (n_11));
  INVX1 g840(.A (n_10), .Y (n_9));
  AOI22XL g841__4319(.A0 (in[5]), .A1 (n_4), .B0 (in[7]), .B1 (n_38),
       .Y (n_13));
  AOI22XL g842__8428(.A0 (in[2]), .A1 (n_4), .B0 (in[7]), .B1 (n_36),
       .Y (n_12));
  AOI22XL g843__5526(.A0 (in[1]), .A1 (n_4), .B0 (in[7]), .B1 (n_35),
       .Y (n_10));
  AOI22XL g844__6783(.A0 (in[4]), .A1 (n_4), .B0 (in[7]), .B1 (n_40),
       .Y (n_8));
  AOI22XL g845__3680(.A0 (in[3]), .A1 (n_4), .B0 (in[7]), .B1 (n_37),
       .Y (n_7));
  AOI22XL g846__1617(.A0 (in[6]), .A1 (n_4), .B0 (in[7]), .B1 (n_39),
       .Y (r_out[3]));
  NOR2XL g847__2802(.A (in[5]), .B (in[4]), .Y (n_6));
  NOR2XL g848__1705(.A (in[2]), .B (in[1]), .Y (n_5));
  INVX1 g849(.A (in[7]), .Y (n_4));
  INVX1 g850(.A (in[0]), .Y (n_3));
  NOR3BX1 g2__5122(.AN (n_0), .B (n_27), .C (n_1), .Y (n_2));
  NOR3BX1 g851__8246(.AN (n_22), .B (n_17), .C (n_24), .Y (n_1));
  NAND2BX1 g852__7098(.AN (n_21), .B (n_16), .Y (n_0));
  XNOR2X1 SUB_UNS_OP_g100__6131(.A (SUB_UNS_OP_n_10), .B (in[6]), .Y
       (n_39));
  AOI21XL SUB_UNS_OP_g101__1881(.A0 (in[5]), .A1 (SUB_UNS_OP_n_8), .B0
       (SUB_UNS_OP_n_10), .Y (n_38));
  NOR2XL SUB_UNS_OP_g102__5115(.A (in[5]), .B (SUB_UNS_OP_n_8), .Y
       (SUB_UNS_OP_n_10));
  OA21X1 SUB_UNS_OP_g103__7482(.A0 (SUB_UNS_OP_n_1), .A1
       (SUB_UNS_OP_n_6), .B0 (SUB_UNS_OP_n_8), .Y (n_40));
  NAND2XL SUB_UNS_OP_g104__4733(.A (SUB_UNS_OP_n_1), .B
       (SUB_UNS_OP_n_6), .Y (SUB_UNS_OP_n_8));
  AOI21XL SUB_UNS_OP_g105__6161(.A0 (in[3]), .A1 (SUB_UNS_OP_n_4), .B0
       (SUB_UNS_OP_n_6), .Y (n_37));
  NOR2XL SUB_UNS_OP_g106__9315(.A (in[3]), .B (SUB_UNS_OP_n_4), .Y
       (SUB_UNS_OP_n_6));
  OA21X1 SUB_UNS_OP_g107__9945(.A0 (SUB_UNS_OP_n_0), .A1
       (SUB_UNS_OP_n_2), .B0 (SUB_UNS_OP_n_4), .Y (n_36));
  NAND2XL SUB_UNS_OP_g108__2883(.A (SUB_UNS_OP_n_0), .B
       (SUB_UNS_OP_n_2), .Y (SUB_UNS_OP_n_4));
  AOI21XL SUB_UNS_OP_g109__2346(.A0 (in[1]), .A1 (in[0]), .B0
       (SUB_UNS_OP_n_2), .Y (n_35));
  NOR2XL SUB_UNS_OP_g110__1666(.A (in[1]), .B (in[0]), .Y
       (SUB_UNS_OP_n_2));
  INVX1 SUB_UNS_OP_g111(.A (in[4]), .Y (SUB_UNS_OP_n_1));
  INVX1 SUB_UNS_OP_g112(.A (in[2]), .Y (SUB_UNS_OP_n_0));
endmodule

