
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 20 2024 13:11:51 IST (Nov 20 2024 07:41:51 UTC)

// Verification Directory fv/lod_8_1_decoder 

module lod_2_1_3_11(vld, k, in);
  input [1:0] in;
  output vld, k;
  wire [1:0] in;
  wire vld, k;
  OR2X1 g18__2398(.A (in[1]), .B (in[0]), .Y (vld));
  NOR2BX1 g19__5107(.AN (in[0]), .B (in[1]), .Y (k));
endmodule

module lod_2_1_3_10(vld, k, in);
  input [1:0] in;
  output vld, k;
  wire [1:0] in;
  wire vld, k;
  OR2X1 g18__6260(.A (in[1]), .B (in[0]), .Y (vld));
  NOR2BX1 g19__4319(.AN (in[0]), .B (in[1]), .Y (k));
endmodule

module lod_8_1(vld, k, in);
  input [7:0] in;
  output vld;
  output [2:0] k;
  wire [7:0] in;
  wire vld;
  wire [2:0] k;
  wire k1, k2, n_0, n_1, n_2, n_3, v1, v2;
  assign vld = 1'b0;
  lod_2_1_3_11 three(v2, k2, in[5:4]);
  lod_2_1_3_10 two(v1, k1, in[3:2]);
  NAND2XL g130__8428(.A (n_2), .B (n_3), .Y (k[0]));
  AOI32X1 g131__5526(.A0 (k1), .A1 (v1), .A2 (k[2]), .B0 (k[2]), .B1
       (n_1), .Y (n_3));
  AOI21XL g132__6783(.A0 (v1), .A1 (n_0), .B0 (in[6]), .Y (k[1]));
  AOI21XL g133__3680(.A0 (v2), .A1 (k2), .B0 (in[6]), .Y (n_2));
  NOR2XL g134__1617(.A (in[6]), .B (v2), .Y (k[2]));
  NOR2XL g135__2802(.A (in[1]), .B (v1), .Y (n_1));
  INVXL g136(.A (v2), .Y (n_0));
endmodule

module lod_8_1_decoder(sign, regi, expo, frac, allone, allzero, in,
     inf);
  input [7:0] in;
  output sign, expo, allone, allzero, inf;
  output [3:0] regi, frac;
  wire [7:0] in;
  wire sign, expo, allone, allzero, inf;
  wire [3:0] regi, frac;
  wire [7:0] lod_in;
  wire [2:0] k;
  wire SUB_UNS_OP_n_0, SUB_UNS_OP_n_1, SUB_UNS_OP_n_2, SUB_UNS_OP_n_4,
       SUB_UNS_OP_n_6, SUB_UNS_OP_n_8, SUB_UNS_OP_n_10,
       dec_sub_45_19_n_0;
  wire dec_sub_45_19_n_1, dec_sub_45_19_n_4, n_0, n_1, n_2, n_3, n_4,
       n_5;
  wire n_6, n_7, n_8, n_9, n_10, n_11, n_12, n_13;
  wire n_14, n_15, n_16, n_17, n_18, n_19, n_20, n_21;
  wire n_22, n_23, n_24, n_25, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, vld;
  assign sign = in[7];
  lod_8_1 l0(vld, k, {1'b0, lod_in[6:1], 1'b1});
  CLKXOR2X1 g324__1705(.A (n_34), .B (n_32), .Y (lod_in[5]));
  CLKXOR2X1 g325__5122(.A (n_34), .B (n_31), .Y (lod_in[4]));
  MX2X1 g326__8246(.A (in[6]), .B (n_43), .S0 (in[7]), .Y (n_34));
  MX2X1 g327__7098(.A (in[3]), .B (n_40), .S0 (in[7]), .Y (n_31));
  MX2X1 g328__6131(.A (in[4]), .B (n_41), .S0 (in[7]), .Y (n_32));
  OAI221X1 g377__1881(.A0 (n_12), .A1 (n_21), .B0 (n_11), .B1 (n_20),
       .C0 (n_24), .Y (frac[3]));
  OAI211X1 g378__5115(.A0 (n_11), .A1 (n_21), .B0 (n_25), .C0 (n_7), .Y
       (expo));
  AOI221X1 g379__7482(.A0 (n_33), .A1 (n_17), .B0 (n_32), .B1 (n_15),
       .C0 (n_23), .Y (n_25));
  OAI222XL g380__4733(.A0 (n_9), .A1 (n_16), .B0 (n_11), .B1 (n_14),
       .C0 (n_12), .C1 (n_19), .Y (frac[1]));
  AOI222X1 g381__6161(.A0 (n_32), .A1 (n_17), .B0 (n_31), .B1 (n_15),
       .C0 (n_37), .C1 (n_18), .Y (n_24));
  OAI221X1 g382__9315(.A0 (n_11), .A1 (n_19), .B0 (n_12), .B1 (n_20),
       .C0 (n_22), .Y (frac[2]));
  OAI22XL g383__9945(.A0 (n_10), .A1 (n_19), .B0 (n_9), .B1 (n_20), .Y
       (n_23));
  AOI22XL g384__2883(.A0 (n_31), .A1 (n_17), .B0 (n_37), .B1 (n_15), .Y
       (n_22));
  OAI22XL g385__2346(.A0 (n_11), .A1 (n_16), .B0 (n_12), .B1 (n_14), .Y
       (frac[0]));
  INVX1 g386(.A (n_19), .Y (n_18));
  INVX1 g387(.A (n_17), .Y (n_16));
  INVX1 g388(.A (n_15), .Y (n_14));
  NAND3BXL g389__1666(.AN (k[1]), .B (n_8), .C (k[2]), .Y (n_21));
  NAND3BXL g390__7410(.AN (k[2]), .B (k[0]), .C (k[1]), .Y (n_20));
  NAND3BXL g391__6417(.AN (k[2]), .B (n_8), .C (k[1]), .Y (n_19));
  NOR2BX1 g392__5477(.AN (n_13), .B (k[0]), .Y (n_17));
  AND2X1 g393__2398(.A (k[0]), .B (n_13), .Y (n_15));
  XNOR2X1 g394__5107(.A (n_34), .B (n_29), .Y (regi[2]));
  XNOR2X1 g395__6260(.A (n_34), .B (n_28), .Y (regi[1]));
  XNOR2X1 g396__4319(.A (n_34), .B (n_30), .Y (regi[3]));
  NOR2XL g399__8428(.A (k[2]), .B (k[1]), .Y (n_13));
  INVX1 g400(.A (in[0]), .Y (n_12));
  INVX1 g401(.A (n_36), .Y (n_11));
  INVXL g404(.A (n_31), .Y (n_10));
  INVX1 g405(.A (n_37), .Y (n_9));
  INVX1 g406(.A (k[0]), .Y (n_8));
  NAND4BXL g2__5526(.AN (k[1]), .B (in[0]), .C (k[2]), .D (k[0]), .Y
       (n_7));
  MXI2XL g407__6783(.A (n_8), .B (k[0]), .S0 (n_34), .Y (regi[0]));
  NOR4BBX1 g371__3680(.AN (n_36), .BN (n_37), .C (n_1), .D (n_6), .Y
       (allone));
  NAND4XL g372__1617(.A (n_32), .B (n_31), .C (n_34), .D (n_33), .Y
       (n_6));
  NOR3BXL g373__2802(.AN (n_4), .B (in[7]), .C (in[6]), .Y (allzero));
  NOR3XL g374__1705(.A (n_5), .B (in[3]), .C (in[0]), .Y (inf));
  MX2X1 g375__5122(.A (n_34), .B (n_0), .S0 (n_33), .Y (lod_in[6]));
  MX2X1 g376__8246(.A (n_34), .B (n_0), .S0 (n_37), .Y (lod_in[3]));
  MX2X1 g408__7098(.A (n_34), .B (n_0), .S0 (n_36), .Y (lod_in[2]));
  NAND4BXL g409__6131(.AN (in[6]), .B (n_3), .C (n_2), .D (in[7]), .Y
       (n_5));
  NOR4BBX1 g410__1881(.AN (n_3), .BN (n_2), .C (in[0]), .D (in[3]), .Y
       (n_4));
  OAI22XL g411__5115(.A0 (n_1), .A1 (n_34), .B0 (n_0), .B1 (in[0]), .Y
       (lod_in[1]));
  MX2X1 g412__7482(.A (in[1]), .B (n_38), .S0 (in[7]), .Y (n_36));
  MX2X1 g413__4733(.A (in[2]), .B (n_39), .S0 (in[7]), .Y (n_37));
  MX2X1 g414__6161(.A (in[5]), .B (n_42), .S0 (in[7]), .Y (n_33));
  NOR2XL g415__9315(.A (in[5]), .B (in[4]), .Y (n_3));
  NOR2XL g416__9945(.A (in[2]), .B (in[1]), .Y (n_2));
  INVX1 g417(.A (in[0]), .Y (n_1));
  INVX1 g418(.A (n_34), .Y (n_0));
  XNOR2X1 SUB_UNS_OP_g100__2883(.A (SUB_UNS_OP_n_10), .B (in[6]), .Y
       (n_43));
  AOI21XL SUB_UNS_OP_g101__2346(.A0 (in[5]), .A1 (SUB_UNS_OP_n_8), .B0
       (SUB_UNS_OP_n_10), .Y (n_42));
  NOR2XL SUB_UNS_OP_g102__1666(.A (in[5]), .B (SUB_UNS_OP_n_8), .Y
       (SUB_UNS_OP_n_10));
  OA21X1 SUB_UNS_OP_g103__7410(.A0 (SUB_UNS_OP_n_1), .A1
       (SUB_UNS_OP_n_6), .B0 (SUB_UNS_OP_n_8), .Y (n_41));
  NAND2XL SUB_UNS_OP_g104__6417(.A (SUB_UNS_OP_n_1), .B
       (SUB_UNS_OP_n_6), .Y (SUB_UNS_OP_n_8));
  AOI21XL SUB_UNS_OP_g105__5477(.A0 (in[3]), .A1 (SUB_UNS_OP_n_4), .B0
       (SUB_UNS_OP_n_6), .Y (n_40));
  NOR2XL SUB_UNS_OP_g106__2398(.A (in[3]), .B (SUB_UNS_OP_n_4), .Y
       (SUB_UNS_OP_n_6));
  OA21X1 SUB_UNS_OP_g107__5107(.A0 (SUB_UNS_OP_n_0), .A1
       (SUB_UNS_OP_n_2), .B0 (SUB_UNS_OP_n_4), .Y (n_39));
  NAND2XL SUB_UNS_OP_g108__6260(.A (SUB_UNS_OP_n_0), .B
       (SUB_UNS_OP_n_2), .Y (SUB_UNS_OP_n_4));
  AOI21XL SUB_UNS_OP_g109__4319(.A0 (in[1]), .A1 (in[0]), .B0
       (SUB_UNS_OP_n_2), .Y (n_38));
  NOR2XL SUB_UNS_OP_g110__8428(.A (in[1]), .B (in[0]), .Y
       (SUB_UNS_OP_n_2));
  INVX1 SUB_UNS_OP_g111(.A (in[4]), .Y (SUB_UNS_OP_n_1));
  INVX1 SUB_UNS_OP_g112(.A (in[2]), .Y (SUB_UNS_OP_n_0));
  INVX1 dec_sub_45_19_g39(.A (dec_sub_45_19_n_4), .Y (n_29));
  ADDHX1 dec_sub_45_19_g40__5526(.A (dec_sub_45_19_n_0), .B
       (dec_sub_45_19_n_1), .CO (n_30), .S (dec_sub_45_19_n_4));
  AO21X1 dec_sub_45_19_g41__6783(.A0 (k[1]), .A1 (k[0]), .B0
       (dec_sub_45_19_n_1), .Y (n_28));
  NOR2XL dec_sub_45_19_g42__3680(.A (k[1]), .B (k[0]), .Y
       (dec_sub_45_19_n_1));
  INVX1 dec_sub_45_19_g43(.A (k[2]), .Y (dec_sub_45_19_n_0));
endmodule

