
// Generated by Cadence Genus(TM) Synthesis Solution 21.10-p002_1
// Generated on: Nov 20 2024 13:10:24 IST (Nov 20 2024 07:40:24 UTC)

// Verification Directory fv/lod_16_1_decoder 

module lod_2_1_7_25(vld, k, in);
  input [1:0] in;
  output vld, k;
  wire [1:0] in;
  wire vld, k;
  OR2X1 g18__2398(.A (in[1]), .B (in[0]), .Y (vld));
  NOR2BX1 g19__5107(.AN (in[0]), .B (in[1]), .Y (k));
endmodule

module lod_2_1_7_24(vld, k, in);
  input [1:0] in;
  output vld, k;
  wire [1:0] in;
  wire vld, k;
  OR2X1 g18__6260(.A (in[1]), .B (in[0]), .Y (vld));
  NOR2BX1 g19__4319(.AN (in[0]), .B (in[1]), .Y (k));
endmodule

module lod_2_1_7_27(vld, k, in);
  input [1:0] in;
  output vld, k;
  wire [1:0] in;
  wire vld, k;
  OR2X1 g18__8428(.A (in[1]), .B (in[0]), .Y (vld));
  NOR2BX1 g19__5526(.AN (in[0]), .B (in[1]), .Y (k));
endmodule

module lod_2_1_7_26(vld, k, in);
  input [1:0] in;
  output vld, k;
  wire [1:0] in;
  wire vld, k;
  OR2X1 g18__6783(.A (in[1]), .B (in[0]), .Y (vld));
  NOR2BX1 g19__3680(.AN (in[0]), .B (in[1]), .Y (k));
endmodule

module lod_2_1_7_23(vld, k, in);
  input [1:0] in;
  output vld, k;
  wire [1:0] in;
  wire vld, k;
  OR2X1 g18__1617(.A (in[1]), .B (in[0]), .Y (vld));
  NOR2BX1 g19__2802(.AN (in[0]), .B (in[1]), .Y (k));
endmodule

module lod_2_1_7_22(vld, k, in);
  input [1:0] in;
  output vld, k;
  wire [1:0] in;
  wire vld, k;
  OR2X1 g18__1705(.A (in[1]), .B (in[0]), .Y (vld));
  NOR2BX1 g19__5122(.AN (in[0]), .B (in[1]), .Y (k));
endmodule

module lod_16_1(vld, k, in);
  input [15:0] in;
  output vld;
  output [3:0] k;
  wire [15:0] in;
  wire vld;
  wire [3:0] k;
  wire \k0[1] , \k0[2] , \k0[3] , \k0[4] , \k0[5] , \k0[6] , n_0, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_13, n_14, n_15, n_16, \v0[1] ;
  wire \v0[2] , \v0[3] , \v0[4] , \v0[5] , \v0[6] ;
  lod_2_1_7_25 five(\v0[4] , \k0[4] , in[9:8]);
  lod_2_1_7_24 four(\v0[3] , \k0[3] , in[7:6]);
  lod_2_1_7_27 seven(\v0[6] , \k0[6] , in[13:12]);
  lod_2_1_7_26 six(\v0[5] , \k0[5] , in[11:10]);
  lod_2_1_7_23 three(\v0[2] , \k0[2] , in[5:4]);
  lod_2_1_7_22 two(\v0[1] , \k0[1] , in[3:2]);
  OR2X1 g312__8246(.A (n_16), .B (n_15), .Y (k[0]));
  NAND2XL g313__7098(.A (n_14), .B (n_10), .Y (n_16));
  OAI211X1 g314__6131(.A0 (in[1]), .A1 (n_11), .B0 (n_12), .C0 (n_4),
       .Y (n_15));
  AOI31X1 g315__1881(.A0 (\v0[1] ), .A1 (\k0[1] ), .A2 (n_9), .B0
       (in[14]), .Y (n_14));
  NAND3X1 g316__5115(.A (n_13), .B (n_5), .C (n_7), .Y (k[1]));
  AND2X1 g317__7482(.A (n_2), .B (n_11), .Y (n_13));
  AOI33XL g318__4733(.A0 (\k0[2] ), .A1 (\v0[2] ), .A2 (n_6), .B0
       (\k0[4] ), .B1 (\v0[4] ), .B2 (n_3), .Y (n_12));
  NAND2BXL g319__6161(.AN (\v0[1] ), .B (n_9), .Y (n_11));
  OAI21XL g320__9315(.A0 (n_1), .A1 (k[3]), .B0 (n_8), .Y (k[2]));
  AOI33XL g321__9945(.A0 (\k0[3] ), .A1 (\v0[3] ), .A2 (k[3]), .B0
       (\v0[5] ), .B1 (\k0[5] ), .B2 (n_0), .Y (n_10));
  INVXL g322(.A (n_9), .Y (n_8));
  NOR2BX1 g323__2883(.AN (n_6), .B (\v0[2] ), .Y (n_9));
  NAND2XL g324__2346(.A (\v0[2] ), .B (n_6), .Y (n_7));
  NOR2BX1 g325__1666(.AN (k[3]), .B (\v0[3] ), .Y (n_6));
  NAND2XL g326__7410(.A (\v0[4] ), .B (n_3), .Y (n_5));
  NOR3X1 g327__6417(.A (\v0[4] ), .B (\v0[5] ), .C (n_1), .Y (k[3]));
  NAND2BXL g328__5477(.AN (n_2), .B (\k0[6] ), .Y (n_4));
  NOR2XL g329__2398(.A (\v0[5] ), .B (n_1), .Y (n_3));
  NAND2BXL g330__5107(.AN (in[14]), .B (\v0[6] ), .Y (n_2));
  INVXL g331(.A (n_1), .Y (n_0));
  OR2X1 g332__6260(.A (in[14]), .B (\v0[6] ), .Y (n_1));
endmodule

module lod_16_1_decoder(sign, regi, expo, frac, allone, allzero, in,
     inf);
  input [15:0] in;
  output sign, expo, allone, allzero, inf;
  output [4:0] regi;
  output [11:0] frac;
  wire [15:0] in;
  wire sign, expo, allone, allzero, inf;
  wire [4:0] regi;
  wire [11:0] frac;
  wire [15:0] lod_in;
  wire [3:0] k;
  wire SUB_UNS_OP_n_0, SUB_UNS_OP_n_1, SUB_UNS_OP_n_2, SUB_UNS_OP_n_3,
       SUB_UNS_OP_n_4, SUB_UNS_OP_n_5, SUB_UNS_OP_n_6, SUB_UNS_OP_n_8;
  wire SUB_UNS_OP_n_10, SUB_UNS_OP_n_12, SUB_UNS_OP_n_14,
       SUB_UNS_OP_n_16, SUB_UNS_OP_n_18, SUB_UNS_OP_n_20,
       SUB_UNS_OP_n_22, SUB_UNS_OP_n_24;
  wire SUB_UNS_OP_n_26, SUB_UNS_OP_n_28, SUB_UNS_OP_n_30,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, dec_sub_49_19_n_0,
       dec_sub_49_19_n_2, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_67, n_68, n_69, n_70, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_77, n_78, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_97, n_98, n_101, n_102, n_103, n_104, n_106, n_107;
  wire n_108, n_109, n_110, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_126, n_127, n_128, n_129, n_130, n_131;
  wire n_132, n_133, vld;
  assign sign = in[15];
  lod_16_1 l0(vld, k, {UNCONNECTED_HIER_Z0, lod_in[14:1],
       UNCONNECTED_HIER_Z});
  CLKXOR2X1 g651__4319(.A (n_119), .B (n_107), .Y (lod_in[3]));
  CLKXOR2X1 g652__8428(.A (n_119), .B (n_106), .Y (lod_in[2]));
  MX2X1 g653__5526(.A (in[14]), .B (n_133), .S0 (in[15]), .Y (n_119));
  MX2X1 g654__6783(.A (in[1]), .B (n_120), .S0 (in[15]), .Y (n_106));
  MX2X1 g655__3680(.A (in[2]), .B (n_121), .S0 (in[15]), .Y (n_107));
  CLKXOR2X1 g642__1617(.A (n_119), .B (n_113), .Y (lod_in[9]));
  CLKXOR2X1 g643__2802(.A (n_119), .B (n_112), .Y (lod_in[8]));
  MX2X1 g644__1705(.A (in[8]), .B (n_127), .S0 (in[15]), .Y (n_113));
  MX2X1 g645__5122(.A (in[7]), .B (n_126), .S0 (in[15]), .Y (n_112));
  CLKXOR2X1 g656__8246(.A (n_119), .B (n_115), .Y (lod_in[11]));
  CLKXOR2X1 g657__7098(.A (n_119), .B (n_114), .Y (lod_in[10]));
  MX2X1 g658__6131(.A (in[10]), .B (n_129), .S0 (in[15]), .Y (n_115));
  MX2X1 g646__1881(.A (in[9]), .B (n_128), .S0 (in[15]), .Y (n_114));
  CLKXOR2X1 g659__5115(.A (n_119), .B (n_109), .Y (lod_in[5]));
  CLKXOR2X1 g660__7482(.A (n_119), .B (n_108), .Y (lod_in[4]));
  MX2X1 g661__4733(.A (in[4]), .B (n_123), .S0 (in[15]), .Y (n_109));
  MX2X1 g647__6161(.A (in[3]), .B (n_122), .S0 (in[15]), .Y (n_108));
  AND3XL g729__9315(.A (n_98), .B (n_107), .C (n_106), .Y (allone));
  NOR4X1 g730__9945(.A (n_90), .B (n_95), .C (n_97), .D (n_96), .Y
       (n_98));
  NAND4XL g731__2883(.A (n_117), .B (n_116), .C (n_119), .D (n_118), .Y
       (n_97));
  NAND4XL g732__2346(.A (n_109), .B (n_108), .C (n_111), .D (n_110), .Y
       (n_96));
  MX2X1 g733__1666(.A (n_119), .B (n_89), .S0 (n_118), .Y (lod_in[14]));
  MX2X1 g734__7410(.A (n_119), .B (n_89), .S0 (n_111), .Y (lod_in[7]));
  XNOR2X1 g735__6417(.A (n_110), .B (n_89), .Y (lod_in[6]));
  AND4XL g736__5477(.A (n_88), .B (n_92), .C (n_94), .D (n_93), .Y
       (inf));
  AND4XL g737__2398(.A (n_94), .B (n_93), .C (n_92), .D (n_91), .Y
       (allzero));
  OAI22XL g738__5107(.A0 (n_90), .A1 (n_119), .B0 (n_89), .B1 (in[0]),
       .Y (lod_in[1]));
  NAND4XL g739__6260(.A (n_113), .B (n_112), .C (n_115), .D (n_114), .Y
       (n_95));
  MX2X1 g740__4319(.A (in[6]), .B (n_125), .S0 (in[15]), .Y (n_111));
  MX2X1 g741__8428(.A (in[5]), .B (n_124), .S0 (in[15]), .Y (n_110));
  MX2X1 g742__5526(.A (in[13]), .B (n_132), .S0 (in[15]), .Y (n_118));
  NOR4X1 g744__6783(.A (in[15]), .B (in[2]), .C (in[1]), .D (in[0]), .Y
       (n_91));
  NOR4X1 g745__3680(.A (in[14]), .B (in[13]), .C (in[12]), .D (in[11]),
       .Y (n_94));
  NOR4X1 g746__1617(.A (in[10]), .B (in[9]), .C (in[8]), .D (in[7]), .Y
       (n_93));
  NOR4X1 g747__2802(.A (in[6]), .B (in[5]), .C (in[4]), .D (in[3]), .Y
       (n_92));
  INVX1 g748(.A (in[0]), .Y (n_90));
  INVX1 g750(.A (n_119), .Y (n_89));
  NOR4BX1 g2__1705(.AN (in[15]), .B (in[2]), .C (in[1]), .D (in[0]), .Y
       (n_88));
  CLKXOR2X1 g641__5122(.A (n_119), .B (n_117), .Y (lod_in[13]));
  CLKXOR2X1 g751__8246(.A (n_119), .B (n_116), .Y (lod_in[12]));
  MX2X1 g752__7098(.A (in[12]), .B (n_131), .S0 (in[15]), .Y (n_117));
  MX2X1 g753__6131(.A (in[11]), .B (n_130), .S0 (in[15]), .Y (n_116));
  NAND4XL g903__1881(.A (n_14), .B (n_49), .C (n_71), .D (n_86), .Y
       (expo));
  OAI211X1 g904__5115(.A0 (n_0), .A1 (n_33), .B0 (n_85), .C0 (n_51), .Y
       (frac[10]));
  NAND4BXL g905__7482(.AN (n_81), .B (n_68), .C (n_67), .D (n_38), .Y
       (frac[11]));
  INVXL g906(.A (n_87), .Y (frac[8]));
  OAI211X1 g907__4733(.A0 (n_5), .A1 (n_23), .B0 (n_74), .C0 (n_82), .Y
       (frac[9]));
  AOI221X1 g908__6161(.A0 (n_114), .A1 (n_27), .B0 (n_106), .B1 (n_34),
       .C0 (n_84), .Y (n_87));
  AOI21XL g909__9315(.A0 (n_106), .A1 (n_25), .B0 (n_80), .Y (n_86));
  AOI21XL g910__9945(.A0 (n_106), .A1 (n_35), .B0 (n_83), .Y (n_85));
  NAND4XL g911__2883(.A (n_37), .B (n_79), .C (n_55), .D (n_61), .Y
       (frac[7]));
  NAND4XL g912__2346(.A (n_50), .B (n_47), .C (n_46), .D (n_41), .Y
       (n_84));
  NAND4XL g913__1666(.A (n_54), .B (n_44), .C (n_40), .D (n_58), .Y
       (frac[6]));
  OAI211X1 g914__7410(.A0 (n_4), .A1 (n_30), .B0 (n_78), .C0 (n_53), .Y
       (frac[5]));
  OAI221X1 g915__6417(.A0 (n_5), .A1 (n_28), .B0 (n_4), .B1 (n_21), .C0
       (n_77), .Y (frac[4]));
  NAND4XL g916__5477(.A (n_57), .B (n_48), .C (n_62), .D (n_66), .Y
       (n_83));
  OAI221X1 g917__2398(.A0 (n_4), .A1 (n_28), .B0 (n_5), .B1 (n_20), .C0
       (n_76), .Y (frac[3]));
  AND4XL g918__5107(.A (n_52), .B (n_43), .C (n_59), .D (n_70), .Y
       (n_82));
  NAND4XL g919__6260(.A (n_60), .B (n_75), .C (n_63), .D (n_64), .Y
       (n_81));
  NAND4XL g920__4319(.A (n_65), .B (n_73), .C (n_72), .D (n_69), .Y
       (n_80));
  AOI221X1 g921__8428(.A0 (n_111), .A1 (n_18), .B0 (n_110), .B1 (n_19),
       .C0 (n_56), .Y (n_79));
  AOI221X1 g922__5526(.A0 (n_109), .A1 (n_18), .B0 (n_108), .B1 (n_19),
       .C0 (n_42), .Y (n_78));
  AOI221X1 g923__6783(.A0 (n_110), .A1 (n_27), .B0 (n_109), .B1 (n_16),
       .C0 (n_39), .Y (n_77));
  OAI221X1 g924__3680(.A0 (n_5), .A1 (n_17), .B0 (n_4), .B1 (n_20), .C0
       (n_45), .Y (frac[2]));
  AOI222X1 g925__1617(.A0 (n_107), .A1 (n_18), .B0 (n_109), .B1 (n_27),
       .C0 (n_108), .C1 (n_16), .Y (n_76));
  OAI222XL g926__2802(.A0 (n_5), .A1 (n_15), .B0 (n_6), .B1 (n_26), .C0
       (n_4), .C1 (n_17), .Y (frac[1]));
  AOI22XL g927__1705(.A0 (n_115), .A1 (n_18), .B0 (n_114), .B1 (n_19),
       .Y (n_75));
  AOI22XL g928__5122(.A0 (n_107), .A1 (n_34), .B0 (in[0]), .B1 (n_35),
       .Y (n_74));
  AOI22XL g929__8246(.A0 (n_116), .A1 (n_18), .B0 (n_115), .B1 (n_19),
       .Y (n_73));
  AOI22XL g930__7098(.A0 (n_112), .A1 (n_31), .B0 (n_111), .B1 (n_32),
       .Y (n_72));
  AOI22XL g931__6131(.A0 (n_108), .A1 (n_35), .B0 (n_107), .B1 (n_36),
       .Y (n_71));
  AOI22XL g932__1881(.A0 (n_115), .A1 (n_27), .B0 (n_114), .B1 (n_16),
       .Y (n_70));
  AOI22XL g933__5115(.A0 (n_118), .A1 (n_27), .B0 (n_117), .B1 (n_16),
       .Y (n_69));
  AOI22XL g934__7482(.A0 (n_108), .A1 (n_24), .B0 (n_107), .B1 (n_35),
       .Y (n_68));
  AOI22XL g935__4733(.A0 (n_109), .A1 (n_34), .B0 (in[0]), .B1 (n_25),
       .Y (n_67));
  AOI22XL g936__6161(.A0 (n_116), .A1 (n_27), .B0 (n_115), .B1 (n_16),
       .Y (n_66));
  AOI22XL g937__9315(.A0 (n_114), .A1 (n_29), .B0 (n_113), .B1 (n_22),
       .Y (n_65));
  AOI22XL g938__9945(.A0 (n_117), .A1 (n_27), .B0 (n_116), .B1 (n_16),
       .Y (n_64));
  AOI22XL g939__2883(.A0 (n_111), .A1 (n_31), .B0 (n_110), .B1 (n_32),
       .Y (n_63));
  AOI22XL g940__2346(.A0 (n_110), .A1 (n_31), .B0 (n_109), .B1 (n_32),
       .Y (n_62));
  AOI22XL g941__1666(.A0 (n_113), .A1 (n_27), .B0 (n_112), .B1 (n_16),
       .Y (n_61));
  AOI22XL g942__7410(.A0 (n_113), .A1 (n_29), .B0 (n_112), .B1 (n_22),
       .Y (n_60));
  AOI22XL g943__6417(.A0 (n_109), .A1 (n_31), .B0 (n_108), .B1 (n_32),
       .Y (n_59));
  AOI22XL g944__5477(.A0 (n_112), .A1 (n_27), .B0 (n_111), .B1 (n_16),
       .Y (n_58));
  AOI22XL g945__2398(.A0 (n_112), .A1 (n_29), .B0 (n_111), .B1 (n_22),
       .Y (n_57));
  OAI22XL g946__5107(.A0 (n_1), .A1 (n_28), .B0 (n_0), .B1 (n_21), .Y
       (n_56));
  AOI22XL g947__6260(.A0 (n_107), .A1 (n_31), .B0 (n_106), .B1 (n_32),
       .Y (n_55));
  AOI22XL g948__4319(.A0 (n_106), .A1 (n_31), .B0 (in[0]), .B1 (n_32),
       .Y (n_54));
  AOI22XL g949__8428(.A0 (n_111), .A1 (n_27), .B0 (n_110), .B1 (n_16),
       .Y (n_53));
  AOI22XL g950__5526(.A0 (n_111), .A1 (n_29), .B0 (n_110), .B1 (n_22),
       .Y (n_52));
  AOI22XL g951__6783(.A0 (n_107), .A1 (n_24), .B0 (in[0]), .B1 (n_36),
       .Y (n_51));
  AOI22XL g952__3680(.A0 (n_109), .A1 (n_22), .B0 (n_108), .B1 (n_31),
       .Y (n_50));
  AOI22XL g953__1617(.A0 (n_110), .A1 (n_34), .B0 (n_109), .B1 (n_24),
       .Y (n_49));
  AOI22XL g954__2802(.A0 (n_114), .A1 (n_18), .B0 (n_113), .B1 (n_19),
       .Y (n_48));
  AOI22XL g955__1705(.A0 (n_113), .A1 (n_16), .B0 (n_107), .B1 (n_32),
       .Y (n_47));
  AOI22XL g956__5122(.A0 (n_110), .A1 (n_29), .B0 (n_111), .B1 (n_19),
       .Y (n_46));
  AOI22XL g957__8246(.A0 (n_108), .A1 (n_27), .B0 (n_107), .B1 (n_16),
       .Y (n_45));
  AOI22XL g958__7098(.A0 (n_108), .A1 (n_29), .B0 (n_107), .B1 (n_22),
       .Y (n_44));
  AOI22XL g959__6131(.A0 (n_113), .A1 (n_18), .B0 (n_112), .B1 (n_19),
       .Y (n_43));
  OAI22XL g960__1881(.A0 (n_5), .A1 (n_26), .B0 (n_4), .B1 (n_15), .Y
       (frac[0]));
  OAI22XL g961__5115(.A0 (n_6), .A1 (n_28), .B0 (n_5), .B1 (n_21), .Y
       (n_42));
  AOI22XL g962__7482(.A0 (n_112), .A1 (n_18), .B0 (in[0]), .B1 (n_24),
       .Y (n_41));
  AOI22XL g963__4733(.A0 (n_110), .A1 (n_18), .B0 (n_109), .B1 (n_19),
       .Y (n_40));
  OAI22XL g964__6161(.A0 (n_0), .A1 (n_17), .B0 (n_6), .B1 (n_20), .Y
       (n_39));
  NAND2XL g965__9315(.A (n_106), .B (n_36), .Y (n_38));
  NAND2XL g966__9945(.A (in[0]), .B (n_34), .Y (n_37));
  INVX1 g967(.A (n_34), .Y (n_33));
  INVX1 g968(.A (n_31), .Y (n_30));
  INVX1 g969(.A (n_29), .Y (n_28));
  INVX1 g970(.A (n_27), .Y (n_26));
  NOR2XL g971__2883(.A (n_3), .B (n_12), .Y (n_36));
  NOR2XL g972__2346(.A (k[0]), .B (n_12), .Y (n_35));
  NOR2XL g973__1666(.A (k[0]), .B (n_9), .Y (n_34));
  NOR2XL g974__7410(.A (n_3), .B (n_13), .Y (n_32));
  NOR2XL g975__6417(.A (k[0]), .B (n_13), .Y (n_31));
  NOR2XL g976__5477(.A (k[0]), .B (n_10), .Y (n_29));
  NOR2XL g977__2398(.A (k[0]), .B (n_11), .Y (n_27));
  INVX1 g978(.A (n_24), .Y (n_23));
  INVX1 g979(.A (n_22), .Y (n_21));
  INVX1 g980(.A (n_20), .Y (n_19));
  INVX1 g981(.A (n_18), .Y (n_17));
  INVX1 g982(.A (n_16), .Y (n_15));
  OR4X1 g983__5107(.A (n_3), .B (k[1]), .C (n_4), .D (n_7), .Y (n_14));
  NOR3XL g984__6260(.A (k[0]), .B (k[1]), .C (n_7), .Y (n_25));
  NOR2XL g985__4319(.A (n_3), .B (n_9), .Y (n_24));
  NOR2XL g986__8428(.A (n_3), .B (n_10), .Y (n_22));
  NAND3X1 g987__5526(.A (k[0]), .B (k[1]), .C (n_8), .Y (n_20));
  AND3XL g988__6783(.A (n_3), .B (k[1]), .C (n_8), .Y (n_18));
  NOR2XL g989__3680(.A (n_3), .B (n_11), .Y (n_16));
  NAND3BXL g990__1617(.AN (k[3]), .B (k[1]), .C (k[2]), .Y (n_13));
  NAND3BXL g991__2802(.AN (k[2]), .B (k[1]), .C (k[3]), .Y (n_12));
  NAND2XL g992__1705(.A (n_2), .B (n_8), .Y (n_11));
  NAND3BXL g993__5122(.AN (k[3]), .B (n_2), .C (k[2]), .Y (n_10));
  NAND3BXL g994__8246(.AN (k[2]), .B (n_2), .C (k[3]), .Y (n_9));
  XNOR2X1 g995__7098(.A (n_119), .B (n_104), .Y (regi[4]));
  XNOR2X1 g996__6131(.A (n_119), .B (n_101), .Y (regi[1]));
  XNOR2X1 g997__1881(.A (n_102), .B (n_119), .Y (regi[2]));
  XNOR2X1 g998__5115(.A (n_119), .B (n_103), .Y (regi[3]));
  NOR2XL g1000__7482(.A (k[3]), .B (k[2]), .Y (n_8));
  NAND2XL g1001__4733(.A (k[3]), .B (k[2]), .Y (n_7));
  INVX1 g1003(.A (n_107), .Y (n_6));
  INVX1 g1004(.A (n_106), .Y (n_5));
  INVX1 g1005(.A (in[0]), .Y (n_4));
  INVX1 g1006(.A (k[0]), .Y (n_3));
  INVX1 g1007(.A (k[1]), .Y (n_2));
  INVXL g1008(.A (n_109), .Y (n_1));
  INVX1 g1009(.A (n_108), .Y (n_0));
  MXI2XL g754__6161(.A (n_3), .B (k[0]), .S0 (n_119), .Y (regi[0]));
  XNOR2X1 SUB_UNS_OP_g228__9315(.A (SUB_UNS_OP_n_30), .B (in[14]), .Y
       (n_133));
  AOI21XL SUB_UNS_OP_g229__9945(.A0 (in[13]), .A1 (SUB_UNS_OP_n_28),
       .B0 (SUB_UNS_OP_n_30), .Y (n_132));
  NOR2XL SUB_UNS_OP_g230__2883(.A (in[13]), .B (SUB_UNS_OP_n_28), .Y
       (SUB_UNS_OP_n_30));
  OA21X1 SUB_UNS_OP_g231__2346(.A0 (SUB_UNS_OP_n_2), .A1
       (SUB_UNS_OP_n_26), .B0 (SUB_UNS_OP_n_28), .Y (n_131));
  NAND2XL SUB_UNS_OP_g232__1666(.A (SUB_UNS_OP_n_2), .B
       (SUB_UNS_OP_n_26), .Y (SUB_UNS_OP_n_28));
  AOI21XL SUB_UNS_OP_g233__7410(.A0 (in[11]), .A1 (SUB_UNS_OP_n_24),
       .B0 (SUB_UNS_OP_n_26), .Y (n_130));
  NOR2XL SUB_UNS_OP_g234__6417(.A (in[11]), .B (SUB_UNS_OP_n_24), .Y
       (SUB_UNS_OP_n_26));
  OA21X1 SUB_UNS_OP_g235__5477(.A0 (SUB_UNS_OP_n_5), .A1
       (SUB_UNS_OP_n_22), .B0 (SUB_UNS_OP_n_24), .Y (n_129));
  NAND2XL SUB_UNS_OP_g236__2398(.A (SUB_UNS_OP_n_5), .B
       (SUB_UNS_OP_n_22), .Y (SUB_UNS_OP_n_24));
  AOI21XL SUB_UNS_OP_g237__5107(.A0 (in[9]), .A1 (SUB_UNS_OP_n_20), .B0
       (SUB_UNS_OP_n_22), .Y (n_128));
  NOR2XL SUB_UNS_OP_g238__6260(.A (in[9]), .B (SUB_UNS_OP_n_20), .Y
       (SUB_UNS_OP_n_22));
  OA21X1 SUB_UNS_OP_g239__4319(.A0 (SUB_UNS_OP_n_3), .A1
       (SUB_UNS_OP_n_18), .B0 (SUB_UNS_OP_n_20), .Y (n_127));
  NAND2XL SUB_UNS_OP_g240__8428(.A (SUB_UNS_OP_n_3), .B
       (SUB_UNS_OP_n_18), .Y (SUB_UNS_OP_n_20));
  AOI21XL SUB_UNS_OP_g241__5526(.A0 (in[7]), .A1 (SUB_UNS_OP_n_16), .B0
       (SUB_UNS_OP_n_18), .Y (n_126));
  NOR2XL SUB_UNS_OP_g242__6783(.A (in[7]), .B (SUB_UNS_OP_n_16), .Y
       (SUB_UNS_OP_n_18));
  OA21X1 SUB_UNS_OP_g243__3680(.A0 (SUB_UNS_OP_n_4), .A1
       (SUB_UNS_OP_n_14), .B0 (SUB_UNS_OP_n_16), .Y (n_125));
  NAND2XL SUB_UNS_OP_g244__1617(.A (SUB_UNS_OP_n_4), .B
       (SUB_UNS_OP_n_14), .Y (SUB_UNS_OP_n_16));
  AOI21XL SUB_UNS_OP_g245__2802(.A0 (in[5]), .A1 (SUB_UNS_OP_n_12), .B0
       (SUB_UNS_OP_n_14), .Y (n_124));
  NOR2XL SUB_UNS_OP_g246__1705(.A (in[5]), .B (SUB_UNS_OP_n_12), .Y
       (SUB_UNS_OP_n_14));
  OA21X1 SUB_UNS_OP_g247__5122(.A0 (SUB_UNS_OP_n_0), .A1
       (SUB_UNS_OP_n_10), .B0 (SUB_UNS_OP_n_12), .Y (n_123));
  NAND2XL SUB_UNS_OP_g248__8246(.A (SUB_UNS_OP_n_0), .B
       (SUB_UNS_OP_n_10), .Y (SUB_UNS_OP_n_12));
  AOI21XL SUB_UNS_OP_g249__7098(.A0 (in[3]), .A1 (SUB_UNS_OP_n_8), .B0
       (SUB_UNS_OP_n_10), .Y (n_122));
  NOR2XL SUB_UNS_OP_g250__6131(.A (in[3]), .B (SUB_UNS_OP_n_8), .Y
       (SUB_UNS_OP_n_10));
  OA21X1 SUB_UNS_OP_g251__1881(.A0 (SUB_UNS_OP_n_1), .A1
       (SUB_UNS_OP_n_6), .B0 (SUB_UNS_OP_n_8), .Y (n_121));
  NAND2XL SUB_UNS_OP_g252__5115(.A (SUB_UNS_OP_n_1), .B
       (SUB_UNS_OP_n_6), .Y (SUB_UNS_OP_n_8));
  AOI21XL SUB_UNS_OP_g253__7482(.A0 (in[1]), .A1 (in[0]), .B0
       (SUB_UNS_OP_n_6), .Y (n_120));
  NOR2XL SUB_UNS_OP_g254__4733(.A (in[1]), .B (in[0]), .Y
       (SUB_UNS_OP_n_6));
  INVX1 SUB_UNS_OP_g255(.A (in[10]), .Y (SUB_UNS_OP_n_5));
  INVX1 SUB_UNS_OP_g256(.A (in[6]), .Y (SUB_UNS_OP_n_4));
  INVX1 SUB_UNS_OP_g257(.A (in[8]), .Y (SUB_UNS_OP_n_3));
  INVX1 SUB_UNS_OP_g258(.A (in[12]), .Y (SUB_UNS_OP_n_2));
  INVX1 SUB_UNS_OP_g259(.A (in[2]), .Y (SUB_UNS_OP_n_1));
  INVX1 SUB_UNS_OP_g260(.A (in[4]), .Y (SUB_UNS_OP_n_0));
  AO21X1 dec_sub_49_19_g61__6161(.A0 (k[3]), .A1 (dec_sub_49_19_n_2),
       .B0 (n_104), .Y (n_103));
  NOR2XL dec_sub_49_19_g62__9315(.A (k[3]), .B (dec_sub_49_19_n_2), .Y
       (n_104));
  OAI2BB1X1 dec_sub_49_19_g63__9945(.A0N (k[2]), .A1N
       (dec_sub_49_19_n_0), .B0 (dec_sub_49_19_n_2), .Y (n_102));
  OR2X1 dec_sub_49_19_g64__2883(.A (k[2]), .B (dec_sub_49_19_n_0), .Y
       (dec_sub_49_19_n_2));
  OAI2BB1X1 dec_sub_49_19_g65__2346(.A0N (k[1]), .A1N (k[0]), .B0
       (dec_sub_49_19_n_0), .Y (n_101));
  OR2X1 dec_sub_49_19_g66__1666(.A (k[1]), .B (k[0]), .Y
       (dec_sub_49_19_n_0));
endmodule

